import{a as m,i}from"./assets/vendor-CLTxG5yw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();document.addEventListener("DOMContentLoaded",()=>{const e=document.querySelector(".btn.btn-link"),t="feedbacks";e.addEventListener("click",r=>{r.preventDefault();const n=document.getElementById(t);n&&n.scrollIntoView({behavior:"smooth",block:"start"})})});m.defaults.baseURL="https://furniture-store-v2.b.goit.study/api";async function f(){try{const{data:e}=await m("/categories");return e}catch(e){i.error({message:`${e.message??String(e)}`,position:"topCenter",timeout:3e3,backgroundColor:"#EF4040",messageColor:"white",close:!1})}}f();const E=document.querySelectorAll(".category-card");async function v(e){const t=await f();[...e].forEach((r,n)=>{n!==0&&(r.dataset.id=t[n-1]._id,r.children[0].textContent=t[n-1].name)})}v(E);const L=document.querySelector(".futniture-list"),g=document.querySelector(".category-container");g.addEventListener("click",C);async function C(e){e.preventDefault();const t=e.target.closest(".category-card");if(!g.contains(t)||!t)return;const r=t.dataset.id;let n=1;try{const{data:o}=await m("/furnitures",{params:{page:n,limit:10,category:r}});L.innerHTML=w(o.furnitures)}catch(o){i.error({message:`${o.message??String(o)}`,position:"topCenter",timeout:3e3,backgroundColor:"#EF4040",messageColor:"white",close:!1})}}function w(e){return e.sort((t,r)=>t.price-r.price).map(t=>`
        <li data-id="${t._id}">
            <img class="card-image" src="${t.images[0]}" alt="${t.name}"/>
            <h3 class="card-title">${t.name}</h3>
            <ul class="card-color-container">
                ${(t.color||[]).map(r=>`
                    <li
                    class="card-color-item"
                    style="background-color: ${r}; color: transparent; border: 0.5px solid #d2d0d0;">1
                    </li>
                    `).join("")}               
            </ul>
            <p class="card-price">${t.price.toLocaleString()} грн</p>
            <button class="details-button button">Детальніше</button>
        </li>
    `).join("")}const l=document.getElementById("order-modal"),S=document.getElementById("closeModalBtn"),c=document.getElementById("callback-form");let y=null,h=null;document.addEventListener("click",e=>{const t=e.target.closest(".open-order-modal-btn");t&&(y=t.dataset.productId,h=t.dataset.color,l.style.display="flex",document.body.style.overflow="hidden")});function d(){l.style.display="none",document.body.style.overflow="",c.reset(),b()}S.addEventListener("click",d);l.addEventListener("click",e=>{e.target===l&&d()});document.addEventListener("keydown",e=>{e.key==="Escape"&&l.style.display==="flex"&&d()});function p(e,t){e.style.border="1px solid #6b0609";let r=e.parentNode.querySelector(".input-error-text");r||(r=document.createElement("p"),r.classList.add("input-error-text"),e.parentNode.appendChild(r)),r.textContent=t}function b(){document.querySelectorAll(".input-error-text").forEach(e=>e.remove()),c.querySelectorAll("input, textarea").forEach(e=>{e.style.border="1px solid rgba(8, 12, 9, 0.15)"})}c.addEventListener("submit",async e=>{e.preventDefault(),b();const t=c.name.value.trim();let r=c.phone.value.trim();const n=c.comment.value.trim();let o=!1;if(t||(p(c.name,"Error Text"),o=!0),(!r||!/^\d+$/.test(r))&&(p(c.phone,"Error Text"),o=!0),o)return;r.startsWith("0")&&(r="38"+r);const s={name:t,phone:r,modelId:y,color:h,comment:n||"Чекатиму на зворотний зв'язок для уточнення деталей. Дякую!"};try{const a=await fetch("https://furniture-store-v2.b.goit.study/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(s)}),u=await a.json();if(console.log("Відповідь від сервера:",u),!a.ok){i.error({title:"Помилка!",message:u.message||"Щось пішло не так. Перевірте дані.",position:"topRight"});return}i.success({title:"Успіх!",message:`Замовлення №${u.orderNum} успішно створено!`,position:"topRight"}),d()}catch(a){console.error("Помилка при запиті:",a),i.error({title:"Помилка!",message:"Не вдалося відправити замовлення. Спробуйте пізніше.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
